# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project_5/project_5.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
# IP: The module: 'outputBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project_5/project_5.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/project_5/project_5.srcs/sources_1/ip/outputBuffer/outputBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/project_5/project_5.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
# IP: The module: 'outputBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project_5/project_5.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/project_5/project_5.srcs/sources_1/ip/outputBuffer/outputBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'outputBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
